name = "url-shortener-wordpress-sensia"
main = "src/index.js"
compatibility_date = "2024-05-02"
workers_dev = true

[[kv_namespaces]]
id = "f67b812215d9441da0105dc16b2e4a9c"
binding = "BD_ID"

[vars]
DEFAULT_PAGE = "https://meusensia.com.br"
RECORD_CLICKS = true